### ISSUE TITLE
how to embulk run nested s3 folder

### ISSUE THREAD

**Issue by iceman-k** [embulk/embulk#1016]
Is it possible to run nested S3 folder like:
 /s3-bucket/folder1/001.gz
 /s3-bucket/folder2/001.gz
 /s3-bucket/ ... / 00X.gz
to other service like bigquery, athena etc.

I'd like to know how to recursively export data from S3 by running embulk.

**Comment by hiroyuki-sato** [comment]
Hello, @iceman-k 

Can you try the following?
And you'll find examples here.
https://github.com/embulk/embulk-input-s3#example
Could you ask plugin specific question on the plugin page?

```yaml
in:
  type: s3
  path_prefix: folder # will match folder1,folder2..folderN
  bucket: s3-bucket
```
