### ISSUE TITLE
Question: embulk guess output without output option is stderr

### ISSUE THREAD

**Issue by shigemk2** [embulk/embulk#1017]
### version 

embulk 0.9.7

### overview

I have a question.
When executing `embulk guess` without output option, the result will be stderr.

Here is example. It would put embulk guess result in stderr.

```sh
$ embulk guess ./try1/seed.yml > stdout 2> stderr
```

I saw the stderr output's cause in [source code](https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/EmbulkRunner.java#L206), but I don't know why.

I think embulk wants to distinguish the result from other log like `2018-05-29 18:16:21.225 +0900: Embulk v0.9.7`.

**Comment by hiroyuki-sato** [comment]
Hello, @shigemk2 

Except for original developer, nobody knows the reason.
If you want to know **why**, you need to ask original developer the reason.
It outputs to stderr since embulk-0.1.0.

```
java -jar ../embulk-0.1.0.jar guess hoge/example.yml -o config.yml > /dev/null
in:
  type: file
  paths: [/private/tmp/bb/hoge/csv]
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    header_line: true
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
exec: {}
out: {type: stdout}
```
