### ISSUE TITLE
[Feature Request] date format in path_prefix

### ISSUE THREAD

**Issue by shigemk2** [embulk/embulk#1018]
I want to output files by embulk everyday and add datetime in output files.
For example, I want the output file name to be sample_20180530.csv when I execute embulk on March 30, 2018, but there's no function in current embulk.

Here is example yaml:

```yml
in:
  ....
out:
  type: file
  path_prefix: '/tmp/out/sample_%Y%m%d' # here
  sequence_format: ''
  formatter: {type: csv, header_line: true, charset: UTF-8, newline: CRLF}
```

The other way is using [liquid file](https://gist.github.com/hiroyuki-sato/370ca003b410fb8a8870), but I don't want use liquid file.
