### ISSUE TITLE
Fails with null characters

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk#1081]
I have csv like

```csv
a,b,c
1,[NUL],3
```
where NUL is null-byte string ´\0´ 

trying this with config file
```yaml
in:
  type: file
  path_prefix: test.csv
  parser:
    type: csv
    stop_on_invalid_record: true
    columns:
    - {name: a, type: string}
    - {name: b, type: string}
    - {name: c, type: string}
out:
  type: stdout
```

Fails with `Too few columns` exception on embulk 0.9.7

**Comment by hiroyuki-sato** [comment]
Hello, @kakoni 

Have you ever tried `null_string:` option?

```yaml
in:
  type: file
  path_prefix: test.csv
  parser:
    type: csv
    null_string: # <-- here
    stop_on_invalid_record: true
    columns:
    - {name: a, type: string}
    - {name: b, type: string}
    - {name: c, type: string}
out:
  type: stdout
```

Best regards

**Comment by kakoni** [comment]
Hi @hiroyuki-sato. Yes
I did both
```java 
null_string: '\0'
```

and 

```java 
null_string: 
```

**Comment by hiroyuki-sato** [comment]
Hello, @kakoni 

It may need to modify the codes.

Could you try the following workaround?

* decoder change `\0` to `NULL`.
* CSV parse `NULL` string as NULL.

```yaml
in:
  type: file
  decoders:
    - type: command
      command: "perl -pe 's/\\0/NULL/g'"
  parser:
    type: csv
    delimiter: ','
    null_string: "NULL"
```

Note.

I made the sample data with the following command.

```ruby
ruby -e 'puts "a,b,c"; 1.upto(10){ puts "1,\0,2" }' > sample_01.csv
echo '1,2,3' >> sample_01.csv
```

```yaml
in:
  type: file
  path_prefix: csv/sample_
  decoders:
    - type: command
      command: "perl -pe 's/\\0/NULL/g'"
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: "NULL"
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: a, type: long}
    - {name: b, type: string}
    - {name: c, type: string }
filters:
- type: row
  where: b IS NOT NULL
out: {type: stdout}
```

```
embulk preview config.yml
+--------+----------+----------+
| a:long | b:string | c:string |
+--------+----------+----------+
|      1 |        2 |        3 |
+--------+----------+----------+
```
