### ISSUE TITLE
Accept empty or null strings as timestamps in csv parser

### ISSUE THREAD

**Issue by alexopoulos7** [embulk/embulk#1098]
Issue Type: New Feature Request
--------------------------------

* Accept empty or null strings when parsing timestamps in csv files
* Currently an exception is thrown when empty string is found in a timestamp column.
exception: 
Caused by: org.embulk.standards.CsvParserPlugin$CsvRecordValidateException: org.embulk.spi.time.TimestampParseException: text is null or empty string.
	at org.embulk.standards.CsvParserPlugin$1.timestampColumn(CsvParserPlugin.java:317)
	at org.embulk.spi.Column.visit(Column.java:54)
	at org.embulk.spi.Schema.visitColumns(Schema.java:68)
	at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:261)

**Comment by hiroyuki-sato** [comment]
Hello, @alexopoulos7 

You can use [embulk-filter-timestamp_format](https://github.com/sonots/embulk-filter-timestamp_format) plugin.

`embulk gem install embulk-filter-timestamp_format`

No. 4 `purchase` column is `null`

null_sample_01.csv

```csv
id,account,time,purchase,comment
1,32864,2015-01-27 19:23:49,20150127,embulk
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
3,27559,2015-01-28 02:20:02,20150128,"Embulk ""csv"" parser plugin"
4,11270,2015-01-29 11:54:36,,NULL
```

```yaml
in:
  type: file
  path_prefix: csv/null_sample_
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: string }
    - {name: comment, type: string}
filters:
  - type: timestamp_format
    default_from_timestamp_format: [ "%Y%m%d" ]
    columns:
    - { name: purchase, type: timestamp }

out: {type: stdout}
```

```
embulk preview timestamp_null2.yml

+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC |                         |                       NULL |
+---------+--------------+-------------------------+-------------------------+----------------------------+
```

## Reference

* [Example](https://github.com/hiroyuki-sato/embulk-support/tree/master/twitter_timestamp_null)
