### ISSUE TITLE
Unresolved dependency error when installing embulk-output-command Gem

### ISSUE THREAD

**Issue by matochondrion** [embulk/embulk#1137]
* Write the following environmental information.
* OS version: ubuntu 16.04
* Java version: 1.8.0_201
* Embulk version: embulk 0.9.17
* Your Embulk configuration (YAML):

```
in:
  type: file
  path_prefix: /home/bitnami/workspace/capstone/capstone_project/experiments/embulk/./try1/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}
```

* Plugin versions

```
*** LOCAL GEMS ***

bundler (1.16.0)
did_you_mean (default: 1.0.1)
embulk (0.9.17 java)
jar-dependencies (default: 0.3.10)
jruby-openssl (0.9.21 java)
jruby-readline (1.2.0 java)
json (1.8.3 java)
liquid (4.0.0)
minitest (default: 5.4.1)
msgpack (1.1.0 java)
net-telnet (default: 0.1.1)
power_assert (default: 0.2.3)
psych (2.2.4 java)
rake (default: 10.4.2)
rdoc (default: 4.2.0)
test-unit (default: 3.1.1)
```

* Write all what you did, e.g. your commands executed
I'm following the get Quick Start instructions from the README.md on :
https://github.com/embulk/embulk

Everything worked up until the "Using Plugins" section. Then when I tried to install  the embulk-output-command using the following:

```
embulk gem install embulk-output-command
embulk gem list
```

I get this error:

```
2019-04-03 16:59:28.869 +0000: Embulk v0.9.17

Gem plugin path is: /home/bitnami/.embulk/lib/gems

ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: user requested 'did_you_mean (= 1.2.0)'
```

I've tried installing several other gems and get the same error. 

Also, I'm working with a teammate who is going through the same exercise on a mac, and he's receiving the same error.

Thank you.
