### ISSUE TITLE
Embulk stop on dupplicate record but not on wrong column data

### ISSUE THREAD

**Issue by Ryo51289** [embulk/embulk#1345]
I have following pattern when import csv data to Postgresql
 Pattern#1 Record insert dupplicate
 => Embulk show me error and all records rollback
 Pattern#2 Record has wrong data type, Example I set character "A" in a numeric column
 =>  Embulk show nothing and all records inserted, the wrong data column is set to NULL value
Question: 
 Are there any way to continue the process in case of Pattern#1? I mean it's will ignore the dupplicate records and continue with the new one?
I see the the `stop_on_invalid_record` is false by default, but seem it's only relate data type issue, not constraint problem.

**Comment by hiroyuki-sato** [comment]
Hello, @Ryo51289 

You need to read an issue template before post. Does this question relate to the core?
I can insert the following duplicate entry(multiple id 2 entry) with the following configuration.

```yaml
in:
  type: file
  path_prefix: hoge/csv/sample_
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
#out: {type: stdout}
out:
  type: postgresql
  host: localhost
  user: user
  password: pass
  table: dup_test
  database: embulk_test
  mode: insert
```


```
1,32864,2015-01-27 19:23:49,20150127,embulk
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
3,27559,2015-01-28 02:20:02,20150128,"Embulk ""csv"" parser plugin"
4,11270,2015-01-29 11:54:36,20150129,NULL
```

```
embulk_test=# select * from dup_test;
 id | account |          time          |        purchase        |          comment
----+---------+------------------------+------------------------+----------------------------
  1 |   32864 | 2015-01-28 04:23:49+09 | 2015-01-27 09:00:00+09 | embulk
  2 |   14824 | 2015-01-28 04:01:23+09 | 2015-01-27 09:00:00+09 | embulk jruby
  2 |   14824 | 2015-01-28 04:01:23+09 | 2015-01-27 09:00:00+09 | embulk jruby
  3 |   27559 | 2015-01-28 11:20:02+09 | 2015-01-28 09:00:00+09 | Embulk "csv" parser plugin
  4 |   11270 | 2015-01-29 20:54:36+09 | 2015-01-29 09:00:00+09 |
(5 rows)
```

* embulk: 0.9.23
* java: 1.8.0_251
* OS: macOS 10.15.7
* embulk-output-postgresql: 0.9.0
