### ISSUE TITLE
`A Buffer detected double release() calls.` reproduce steps.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1374]
Issue Type: Bug Report
-----------------------

### Summary

The following steps outputs `A Buffer detected double release() calls.`. After this message, raise the `NullPointerException` exception.

* Write the following environmental information.
  * OS version: macOS 11.1
  * Java version: 1.8.0_251
  * Embulk version: 0.9.23
  * Your Embulk configuration (YAML): see below
  * Plugin versions: see below
    * embulk-filter-expand_json: 0.5.2
    * embulk-filter-flatten_json: 0.0.2

### Write all what you did, e.g. your commands executed

```
curl -O https://raw.githubusercontent.com/hiroyuki-sato/embulk-support/master/20210125_twitter_filter-json_npe/both_filters.yml
curl -O https://raw.githubusercontent.com/hiroyuki-sato/embulk-support/master/20210125_twitter_filter-json_npe/test_data.json
embulk gem install embulk-filter-flatten_json
embulk gem install embulk-filter-expand_json
```

Run `embulk run both_filters.yml`.

### Write what you expected and observed actually

I expected run embulk completely, but It raises the exception.

both_filters.yml

```yaml
in:
  type: file
#  path_prefix: ./test2_data.json
  path_prefix: ./test_data.json
  parser:
    type: none
filters:
  - type: flatten_json
    json_columns:
      - payload
    separator: "__"
    array_index_prefix: "_"
  - type: expand_json
    json_column_name: payload
    expanded_columns:
      - {name: "author__login", type: string}
      - {name: "createdAt", type: string}
      - {name: "additions", type: string}
      - {name: "deletions", type: string}
      - {name: "commits__nodes_0__commit__authoredDate", type: string}
      - {name: "mergedAt", type: string}
      - {name: "title", type: string}
      - {name: "url", type: string}
out:
  type: stdout

exec:
  preview_sample_buffer_bytes: 131072 # 64KB *2
```

```
{"title":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","author":{"login":"XXXXXXXX"},"url":"https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","createdAt":"2021-01-22T23:40:55Z","mergedAt":"2021-01-22T23:47:34Z","additions":2,"deletions":0,"commits":{"nodes":[{"commit":{"authoredDate":"2021-01-22T23:40:23Z"}}]}}
... repeats 199times total 200 lines.
```

It doesn't raise the exception when I use one filter plugin.
And if the input data less than < 64KB. this error doesn't' happen.

| pattern           | config           | result | note              |
|-------------------|------------------|--------|-------------------|
| only expand_json  | only_expand.yml  | OK     |                   |
| only flatten_json | only_expand.yml  | OK     |                   |
| expand + flatten  | both_filters.yml | ERR    |                   |
| expand + flatten  | both_filters.yml | OK     | input data < 64KB |

Ref: https://github.com/hiroyuki-sato/embulk-support/tree/master/20210125_twitter_filter-json_npe

## Also related.

This error may relate to #1218 and #403

## Note

This error reported by: [@koji_mats](https://twitter.com/koji_mats/status/1353253702329487361?s=20). Thank you
