### ISSUE TITLE
csv guess colum name detection behavior

### ISSUE THREAD

**Issue by y-ken** [embulk/embulk#162]
I have expected the column detection like below but It results c0, c1.... 
Would you please improve column name detection behavior?

```
# expected
    columns:
    - {name: ID, type: string}
    - {name: 名前, type: string}
    - {name: 住所, type: string}

# actual
    columns:
    - {name: c0, type: string}
    - {name: c1, type: string}
    - {name: c2, type: string}
```

## input files

All files encodings are utf-8.

```
$ cat << 'EOF' > test.csv
"ID","名前","住所"
"1","あ","北海道"
"2","い","東京"
EOF
```

```
$ cat << 'EOF' > partial-config.yml
in:
  type: file
  path_prefix: ./test.csv
out:
  type: stdout
EOF
```

## guess outputs

```
$ embulk guess partial-config.yml -o config.yml
2015-04-22 10:16:48.650 +0900: Embulk v0.6.2
2015-04-22 10:16:49.384 +0900 [INFO] (guess): Listing local files at directory '.' filtering filename by prefix 'test.csv'
2015-04-22 10:16:49.388 +0900 [INFO] (guess): Loading files [test.csv]
/Users/y-ken/bin/embulk!/embulk/guess/schema_guess.rb:81 warning: already initialized constant TRUE_STRINGS
/Users/y-ken/bin/embulk!/embulk/guess/schema_guess.rb:90 warning: already initialized constant FALSE_STRINGS
/Users/y-ken/bin/embulk!/embulk/guess/schema_guess.rb:98 warning: already initialized constant TYPE_COALESCE
exec: {}
in:
  type: file
  path_prefix: ./test.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: ''
    skip_header_lines: 0
    columns:
    - {name: c0, type: string}
    - {name: c1, type: string}
    - {name: c2, type: string}
out: {type: stdout}

Created 'config.yml' file.
```

**Comment by y-ken** [comment]
Adding an another case of related this issue.

```
$ vim test.csv
"No","種類","地域","市区町村コード"
1,"学生","北海道","01101"
2,"社会人","北海道","01102"
```

it results unexpected quoted column name.

```
exec: {}
in:
  type: file
  path_prefix: ./test.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: ''
    skip_header_lines: 1
    columns:
    - {name: '"No"', type: boolean}
    - {name: '"種類"', type: string}
    - {name: '"地域"', type: string}
    - {name: '"市区町村コード"', type: string}
out: {type: stdout}
```
