### ISSUE TITLE
Issue on timestamp formatting when using timezones

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk#1644]
Embulk 0.11.1

data.csv
`1,Alice,Cooper,31.1.2023,0`

Conf
```
in:
  type: file
  path_prefix: data.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    columns:
      - {name: id, type: long}
      - {name: first_name, type: string}
      - {name: last_name, type: string}
      - {name: birth, type: timestamp, format: '%d.%m.%Y'}
      - {name: dummy, type: long}
out:
  type: stdout
```

Will print
```
1,Alice,Cooper,31.01.2023,0
```

If I add default_timezone
```
in:
  type: file
  path_prefix: /data/data.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    default_timezone: "Europe/Helsinki"
    columns:
      - {name: id, type: long}
      - {name: first_name, type: string}
      - {name: last_name, type: string}
      - {name: birth, type: timestamp, format: '%d.%m.%Y'}
      - {name: dummy, type: long}
out:
  type: stdout
```

I'll get 
```
1,Alice,Cooper,30.01.2023,0
```
