### ISSUE TITLE
Running multiple jobs using one config file

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#167]
We often have this kind of use case:

* Read src_accounts.csv file and write to `accounts` table on PostgreSQL
* Read src_payments.csv file and write to `payments` table on PostgreSQL
* Read src_requests.csv file and write to `requests` table on PostgreSQL

In this case, we need multiple configuration files and multiple `embulk run` commands.
Idea here is to add a simple multi-transaction feature to embulk.

For example, the configuration file can be like this:

```yml
jobs:
    accounts:
    payments:
    requests:
in:
    type: file
    path_prefix: src_${job}
    parser:
        type: csv
out:
    type: postgresql
    table: table_${job}
```

**Comment by hito4t** [comment]
> A concern is that requests and payments won't be rolled back when commit of job accounts fails.

I think it is permissible because it will be rare case (or we should implement commit to rarely fail).
It's enough if an appropriate error message is output when commit fails.

As the example above, same type inputs, same type parsers, same type outputs will be used in multiple jobs.
(On the contrary to the example, multiple table inputs -> multiple file outputs jobs will be also often used.)
But in regards to filters, different types may be used.
For example, filters to validate input values based on the schema of the input may be used.

And I think it's useful to use different character strings for the file name and the table name (ex. acc.csv -> ACCOUNT table).

My idea is as follows:
<pre>
jobs:
    accounts:
        file_name: src_accounts
        table_name: table_accounts
        csv_columns:
            - {name: id, type: long}
            - {name: surename, type: string}
            - {name: givenname, type: string}
        filter_type: filter_accounts
    payments:
        file_name: src_payments
        table_name: table_payments
        csv_columns:
            - {name: id, type: long}
            - {name: timestamp, type: timestamp, format: format: '%Y-%m-%d %H:%M:%S.%N'}
        filter_type: filter_payments
    requests:
        file_name: src_requests
        table_name: table_requests
        csv_columns:
            - {name: request_id, type: string}
            - {name: account_id, type: long}
            - {name: timestamp, type: timestamp, format: format: '%Y-%m-%d %H:%M:%S.%N'}
        filter_type: filter_requests
in:
    type: file
    path_prefix: ${file_name}
    parser:
        type: csv
        columns: ${csv_columns}
    filters:
    - type: ${filter_type}
out:
    type: postgresql
    table: ${table_name}
</pre>

**Comment by frsyuki** [comment]
It's good point that each source files want to use different type of filters.

In my idea above, each jobs will use global configuration + job-specific configuration. Job-specific configurations are merged to (overwrite) global configuration. For example, if `accounts` job has `jobs.accounts.in.parser.columns` setting, it overwrites `in.parser.columns`.

Another thing is `variables` section to defines many variables:

```
jobs:
    accounts:
        variables:
            file_name: src_accounts
            table_name: table_accounts
        in:
            parser:
                type: csv
                columns:
                - {name: id, type: long}
                - {name: surename, type: string}
                - {name: givenname, type: string}
        filters:
            - {type: filter_accounts}
    payments:
        variables:
            file_name: src_payments
            table_name: table_payments
        in:
            parser:
                type: csv
                columns:
                - {name: id, type: long}
                - {name: timestamp, type: timestamp, format: format: '%Y-%m-%d %H:%M:%S.%N'}
        filters:
            - {type: filter_accounts}
    requests:
        variables:
            file_name: src_requests
            table_name: table_requests
        in:
            parser:
                type: csv
                columns:
                - {name: request_id, type: string}
                - {name: account_id, type: long}
                - {name: timestamp, type: timestamp, format: format: '%Y-%m-%d %H:%M:%S.%N'}
        filters:
            - {type: filter_accounts}
in:
    type: file
    path_prefix: ${file_name}
    parser:
        type: csv
out:
    type: postgresql
    table: ${table_name}
```
