### ISSUE TITLE
Multiple inputs and multiple outputs

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#206]
Multiple inputs:

```
in:
  type: example
data:
  myuser:
    type: mysql
    host: xyz
    database: abc
    query: select * from myuser
  myitem:
    type: mysql
    host: xyz
    database: abc
    query: select * from item
filter:
  - type: join
    with: myuser
    key: [user_id, id]
  - type: join
    with: myitem
    key: [item_id, id]
out:
  type: example
```

Multiple outputs:

```
in:
  type: example
filter:
  - type: copy
    out:
      type: mysql
      database: xyz
      table copy1
output:
  type: example
```
