### ISSUE TITLE
Embedding variables in config file

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#245]
In addition to #206, this idea makes it possible to embed variables in config file.
Unlike #206, this idea is based on text processing. Embulk reads a config file, and apply a template engine such as ERB, and load the generated file using YAML. It also means that variables don't have types (all variables are text).

Here is an example:

```
variables:  # declare variables in a config file
  myval: 1
plugin_variables:  # run an input plugin, and use the last (or first) row as variables
  type: postgresql
  query: select max(id) as max_id from access
  database: production
  host: pg_analyze
---
in:
  type: mysql
  query: select id, host, ip from access_source where ${max_id} < id
  database: production
  host: my_tran
out:
  type: postgresql
  table: access
  database: production
  host: pg_analyze
```
