### ISSUE TITLE
Replace config file with command line parameter

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk#253]
It is useful if we can replace placeholders in a config file with command line parameters.

For example, the following config file
<pre>
in:
  type: jdbc
  ...
  query:
    SELECT * FROM ITEM WHERE CATEGORY='${category}'
</pre>
will be replaced by the following command.
<pre>
embulk run config.yml -P category=100
</pre>

**Comment by kakusuke** [comment]
I would like to use environment variables, too.

**Comment by hishidama** [comment]
I would like to use property files, too.

example)
command:
<pre>embulk run config.yml -P jdbc.properties</pre>

config.yml:
<pre>in:
  type: jdbc
  user: ${resource.jdbc.user}
  password: ${resource.jdbc.password}
  ...</pre>

jdbc.properties:
<pre># JDBC
resource.jdbc.user=user
resource.jdbc.password=pass</pre>

**Comment by frsyuki** [comment]
I'm considering to use Liquid as text-based template engine of config file. For example,

command:

```
# liquid template engine is enabled if file name ends with .liquid
embulk run config.yml.liquid -P jdbc.properties --env
```

config.yml.liquid:

```
in:
    type: jdbc
    user: {{resource.jdbc.user | text}}
    user: {{resource.jdbc.password | text}}  # "| text" escapes special characters and surrounds by "
    port: {{env.jdbc_port}}  # "env" is enabled if --env cmdline arg is set
```
