### ISSUE TITLE
Writing one data source to multiple destinations

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#314]
Idea is to creating a special output plugin that invokes multiple output plugins.

**Comment by frsyuki** [comment]
For multiple inputs to multiple outputs (e.g. csv file1 -> postgresql table1, csv file2 -> postgresql table2), an idea is to add another type of guess plugin that generates "multi-action" config file. The special guess plugin generates multiple in: sections and share common configuraiton by using yaml's object reference.
For example,

```yaml
in: &in
  type: mysql
  database: mydb
  user: root
  # table is not here
out: &out
  type: postgresql
  database: mydb
  # table is not here
+action1:
  in:
    <<: *in  
    table: table1
  out:
    <<: *out
    table: table1
+action2:
  in:
    <<: *in  
    table: table1
  out:
    <<: *out
    table: table1
```

where `+XYZ` are the actions that invoke embulk runner.
