### ISSUE TITLE
formatter-csv quotes my JSON field even quote_policy: NONE

### ISSUE THREAD

**Issue by sonots** [embulk/embulk#327]
sample.tsv

```
a[TAB]b[TAB]c[TAB]{"a":1,"b":2}
```

sample.yml

```
in:
  type: file
  path_prefix: sample.tsv
  parser:
    type: csv
    delimiter: "\t"
    quote: null
    escape: null
    columns:
      - {name: column1, type: string}
      - {name: column2, type: string}
      - {name: column3, type: string}
      - {name: column4, type: string}
out:
  type: file
  path_prefix: '/tmp/sample.'
  file_ext: 'csv'
  overwrite: true
  formatter:
    type: csv
    delimiter: "\t"
    quote_policy: NONE
    header_line: false
```

/tmp/sample.000.00.csv becomes as

```
a[TAB]b[TAB]c[TAB]{\"a\":1,\"b\":2}
```

**Comment by sonots** [comment]
What I want to do is to move a file from local to hdfs (actually). 
If parser: none and formatter: none are available, my purpose can be achieved also.

**Comment by sonots** [comment]
Found a same issue from twitter https://twitter.com/hiruandon2nd/status/652400739298381824

**Comment by sakama** [comment]
I implemented CSV formatter's quote and escape process at #168

Currently, behavior of quote_policy will be affected by quote parameter's value.
I think if you set `quote: '0'`, your porpose can be achieved.

Type of quote parameter is char, so empty string or null at config.yml doesn't work.
```yaml
quote: ''
quote: 
```

Set `quote: '0'` means set empty char as quote.

If you set other char, '"' will be set as quote character automatically at following line.
https://github.com/embulk/embulk/blob/master/embulk-standards/src/main/java/org/embulk/standards/CsvFormatterPlugin.java#L110



sample.yml for your sample.tsv
```yaml
in:
  type: file
  path_prefix: sample.tsv
  parser:
    type: csv
    delimiter: "\t"
    quote: null
    escape: null
    columns:
      - {name: column1, type: string}
      - {name: column2, type: string}
      - {name: column3, type: string}
      - {name: column4, type: string}
out:
  type: file
  path_prefix: '/tmp/sample.'
  file_ext: 'csv'
  overwrite: true
  formatter:
    type: csv
    delimiter: "\t"
    quote_policy: NONE
    quote: '0'
    header_line: false
```
