### ISSUE TITLE
How to copy files using remote(scp) or ftp plugin and store it using exact file name from the server

### ISSUE THREAD

**Issue by benbenja** [embulk/embulk#349]
Hi,

      We have a requirement to copy files from remote location either using scp or ftp. Remote location will have ASCII files as well as files compressed with any compression utility (gzip, zip, tar or bzip2). It would be more helpful if someone could get me a example to copy the files from remote location and write it to local hard disk with exact file name.

Thanks in advance.

Regards,
Ben

**Comment by hiroyuki-sato** [comment]
Hello @benbenja

Could you tell me about COPY meaning?

* (a) You want to read files on remote hosts with ftp,scp ?
* (b) You want to copy remote file to local host.

## (a) 

You can use embulk-input-ftp or embulk-input-remote plugin.

* [embulk-input-ftp](https://github.com/embulk/embulk-input-ftp)
* [embulk-input-remote](https://github.com/kamatama41/embulk-input-remote)

This is embulk-input-remote configuration example.

```yaml
in:
  type: remote
  hosts:
    - host1
    - host2
  path: /some/path/app_20150414125923.log
  auth:
    user: kamatama41
    # ssh public key authentication key files
    type: public_key
    key_path: /usr/home/.ssh/id_rsa
#   password authentication.
#    type: password
#    password: {password}
```

## (b)

I don't know to copy file from remote host with Embulk.
I recommend you to use ``wget`` or ``curl`` command for retrieve remote files.
And read it with Embulk.

Regards.

--
Hiroyuki Sato.
