### ISSUE TITLE
CSV output `escape` character does not escape itself

### ISSUE THREAD

**Issue by joeharris76** [embulk/embulk#416]
I'm outputting CSV and have discovered that the specified `escape` character does not escape itself.
```
out:
  type: file
  path_prefix: …
  file_ext: csv.gz
  formatter:
    type: csv
    quote_policy: ALL
    quote: '"'
    escape: "\\"
    null_string: "\\N"
```

I've come across a value where the escape character is at the end of the value and therefore escapes the quote that follows it. For example:
`http://maps.googleapis.com/maps/api/js?key=asdfghjkl&sensor=false\|<null>|Mozilla`
is output as 
`"http://maps.googleapis.com/maps/api/js?key=asdfghjkl&sensor=false\",\N,"Mozilla"`
note the `false\"` where the existing escape character escapes the closing quote.

The escape character needs to look for all instances of itself and escape them as well.
