### ISSUE TITLE
Aurora support? 

### ISSUE THREAD

**Issue by HyderRevolutionParts** [embulk/embulk#442]
Question: Can I use embulk to load data from my Aurora DBs into Redshift? I saw there are input/output plugins for MySQL and Redshift, but I'm not sure if Aurora is included in that?

**Comment by muga** [comment]
I don't try to load data from/to Aurora via Embulk. But, if you can access to Aurora by MySQL JDBC driver, you can use embulk-in/out-mysql to do that. Because embulk-in/out-mysql uses the JDBC driver to access to MySQL.

FYI: http://stackoverflow.com/questions/31250975/what-database-driver-should-be-used-to-access-aws-aurora

**Comment by hiroyuki-sato** [comment]
@HyderRevolutionParts 
I don't try to load from/to Aurora too.
But the author of this blog connects to Amazon Aurora with embulk-output-mysql.
[OpenGroove](http://open-groove.net/embulk/embulk-mariadb-aws-aurora/) (Japanese text).

This is example configuration. 

```yaml
out:
  type: mysql
  host: embulkload-cluster.cluster-************.us-west-2.rds.amazonaws.com
  user: embulktestuser
  password: embulkpasswd
  database: embulktest
  table: access
  mode: insert
```
