### ISSUE TITLE
CSV Input Parser can't parser timestamp by long

### ISSUE THREAD

**Issue by linroex** [embulk/embulk#467]
Hi

When I use embulk read a file, and use CSV Input Parser to parse it, the parser will display:

Skipped line 189 (org.embulk.spi.time.TimestampParseException: Failed to parse '1470148959542')

I try different unit also error, ex second, ns .

Is this a bug? or is this some reason?

**Comment by hiroyuki-sato** [comment]
@linroex 

Does ``1470148959542`` mean ``2016-08-02 14:42:39.542000 +0000`` ?

If so, please try [embulk-filter-timestamp_format](https://github.com/sonots/embulk-filter-timestamp_format)

I tried ``format: "%s%3N`` but It does not work as I expected. so I used that plugin.
(I'll check built-in plugin behavior later.)

```yaml
in:
  type: file
  path_prefix: /private/tmp/hoge/csv/sample_
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: time, type: long}
#    - {name: time, type: timestamp, format: "%s%3N"}
#    - {name: time, type: timestamp, format: "%s%3N"}
filters:
  - type: timestamp_format
    columns:
      - { name: time, from_unit: ms }
out: {type: stdout}
```

```
id,time
1,1470148959542
2,1470148959542
3,1470148959542
4,1470148959542
```

```
+---------+----------------------------------+
| id:long |                      time:string |
+---------+----------------------------------+
|       1 | 2016-08-02 14:42:39.542000 +0000 |
|       2 | 2016-08-02 14:42:39.542000 +0000 |
|       3 | 2016-08-02 14:42:39.542000 +0000 |
|       4 | 2016-08-02 14:42:39.542000 +0000 |
+---------+----------------------------------+
```
