### ISSUE TITLE
json can not be parsed after upgrade to 0.8.13

### ISSUE THREAD

**Issue by fs-wu** [embulk/embulk#469]
I have used 0.7.4 and embulk-input-http and embulk-parser-json to get json data from http and parse the json data such as {"aaa":1,"items":[{"bbb":2, "ccc":3},{"bbb":4, "ccc":5}]}
but after I upgrade to 0.8.13, the data can not be parse and got error.
it look like the internal json plugin conflict with the embulk-parser-json.
How to disable the internal json plugin to use embulk-parser-json? since the current internal json plugin can not do that json data parse.

**Comment by hiroyuki-sato** [comment]
@fs-wu 

Could you show me your configuration?

The built-in JSON plugin does not support JSONPath.
It read all data as JSON column type. 

Maybe I think you can use [embulk-filter-expand_json](https://github.com/civitaspo/embulk-filter-expand_json/commits/master) filter plugin for this purpose.

Additionally, built-in JSON parser and embulk-filter-expand_json is written in Java.
It is faster than the embulk-parser-json(Ruby) plugin. 
So If you use Embulk 0.8.3, I recommend you to use another plugin. 

Finally, as far as I know you can't disable the built-in plugin.

**Comment by hiroyuki-sato** [comment]
@fs-wu 

Here is the one of the example

input data is `{"aaa":1,"items":[{"bbb":2, "ccc":3},{"bbb":4, "ccc":5}]}`

```yaml
in:
  type: file
  path_prefix: input.json
  parser:
    type: json
filters:
  - type: expand_json
    root: "$."
    json_column_name: record
    expanded_columns:
      - { name: "aaa", type: string }
      - { name: "items[0].bbb", type: long }
      - { name: "items[1].ccc", type: long }
  - type: rename
    columns:
      "items[0].bbb": "bbb"
      "items[1].ccc": "ccc"
    
out:
  type: stdout
```

```
+------------+----------+----------+
| aaa:string | bbb:long | ccc:long |
+------------+----------+----------+
|          1 |        2 |        5 |
+------------+----------+----------+
```

**Comment by fs-wu** [comment]
Thank you, I will have a look for expand_json.
Here is my current config:

`
in:
  type: file
  path_prefix: ./tmp/y
  parser:
    type: json
    root: $.items
    schema:
     - {name: goods_id, type: string}
out:
  type: stdout
`

**Comment by hiroyuki-sato** [comment]
Please take a look the above example. 
If you want to know additional usage, please let me know. 

When I answer your questions, I want to know the following the data. 

* Input data example
* Output data format example

I don't use embulk-parser-json much, so I can't imagine the output data.

Thanks.

**Comment by fs-wu** [comment]
my test data:
```
{"count":7,"page":1,"per_page":10000000,"total":7,"sort":"weight desc","total_page":1,"items":[{"pickup_copy":null,"sticker_price":670000,"review_ranking_in_category":10000,"stock":2,"goods_id":811323},{"pickup_copy":null,"sticker_price":550000,"review_ranking_in_category":10000,"stock":2,"goods_id":811318},{"pickup_copy":null,"sticker_price":347000,"review_ranking_in_category":10000,"stock":2,"goods_id":810264},{"pickup_copy":null,"sticker_price":38000,"review_ranking_in_category":10000,"stock":1,"goods_id":810281},{"pickup_copy":null,"sticker_price":39800,"review_ranking_in_category":10000,"stock":2,"goods_id":779196}]}
```

my config:
```
in:
  type: file
  path_prefix: ./tmp/y
  parser:
    type: json
filters:
  - type: expand_json
    json_column_name: record
    root: $.items
    expanded_columns:
     - {name: goods_id, type: string}
out:
  type: stdout
```

but no data get
the result look like that:
```
2016-08-25 09:49:17.801 +0000: Embulk v0.8.13
2016-08-25 09:49:21.610 +0000 [INFO] (0001:transaction): Loaded plugin embulk-filter-expand_json (0.1.3)
2016-08-25 09:49:21.698 +0000 [INFO] (0001:transaction): Listing local files at directory 'tmp' filtering filename by prefix 'y'
2016-08-25 09:49:21.733 +0000 [INFO] (0001:transaction): Loading files [tmp/y]
2016-08-25 09:49:21.841 +0000 [INFO] (0001:transaction): removed column: name: record, type: json, index: 0
2016-08-25 09:49:21.841 +0000 [INFO] (0001:transaction): added column: name: goods_id, type: string, options: {}, index: 0
2016-08-25 09:49:21.852 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=2 / tasks=1
2016-08-25 09:49:21.872 +0000 [INFO] (0001:transaction): {done:  0 / 1, running: 0}

2016-08-25 09:49:22.256 +0000 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2016-08-25 09:49:22.263 +0000 [INFO] (main): Committed.
2016-08-25 09:49:22.267 +0000 [INFO] (main): Next config diff: {"in":{"last_path":"tmp/y"},"out":{}}
```

**Comment by hiroyuki-sato** [comment]
Oh, I see what is your problem. 

The embulk-parser-json extract an array object into multiple records. 
Do you want to extract your data like the following, right?

I have no idea how to do it.
Maybe something needs (disable the built-in plugin, or new plugin) for solve your problem.

| pickup_copy | sticker_price | review_ranking_in_category | stock | goods_id |
|:------------|:--------------|:---------------------------|:------|:---------|
|             | 670000        | 10000                      | 2     | 811323   |
|             | 670000        | 10000                      | 2     | 811323   |
|             | 670000        | 10000                      | 2     | 811323   |
|             | 670000        | 10000                      | 2     | 811323   |
|             | 670000        | 10000                      | 2     | 811323   |
|             | 670000        | 10000                      | 2     | 811323   |

**Comment by hiroyuki-sato** [comment]
I've started to develop [embulk-parser-jsonpath](https://github.com/hiroyuki-sato/embulk-parser-jsonpath/commits?author=hiroyuki-sato) plugin for my Embulk and Java study. 
(I'm studying Java language.)

This plugin will solve your problem. I'll let you know when this plugin release. 
(I'm looking forward reviewer)

Currently, basic parser worked. (no Test)

```yaml
in:
  type: file
  path_prefix: example/input
  parser:
    type: jsonpath
    root: "$.items"
    columns:
      - { name: "pickup_copy", type: long }
      - { name: "sticker_price", type: long }
      - { name: "review_ranking_in_category", type: long }
      - { name: "review_ranking_in_category", type: long }
      - { name: "stock", type: long }
      - { name: "goods_id", type: long }
```

```
+------------------+--------------------+---------------------------------+---------------------------------+------------+---------------+
| pickup_copy:long | sticker_price:long | review_ranking_in_category:long | review_ranking_in_category:long | stock:long | goods_id:long |
+------------------+--------------------+---------------------------------+---------------------------------+------------+---------------+
|                  |            670,000 |                          10,000 |                          10,000 |          2 |       811,323 |
|                  |            550,000 |                          10,000 |                          10,000 |          2 |       811,318 |
|                  |            347,000 |                          10,000 |                          10,000 |          2 |       810,264 |
|                  |             38,000 |                          10,000 |                          10,000 |          1 |       810,281 |
|                  |             39,800 |                          10,000 |                          10,000 |          2 |       779,196 |
+------------------+--------------------+---------------------------------+---------------------------------+------------+---------------+
```
