### ISSUE TITLE
[Redshift-output-jdbc] Insert in a table with IDENTITY column

### ISSUE THREAD

**Issue by Olaktal** [embulk/embulk#477]
Hello !

I'd like to generate unique IDs for each row of my table so I setted up one of my column as IDENTITY(0,1) but I can't see how to configure my YAML file to insert into this table.
I noticed that columns names are not specified in the insert command.

Example: 
Create table test (id IDENTITY(0,1), myCol varchar)

Query during script execution
INSERT INTO "test" (SELECT "col1" FROM "test_7e94300056c8cc0_bl_tmp000" UNION ALL                                                              SELECT "col1" FROM "test_7e94300056c8cc0_bl_tmp001" --> FAIL

And so I guess I'd like to have:

INSERT INTO "test"(myCol) (SELECT "col1" FROM "test_7e94300056c8cc0_bl_tmp000" UNION ALL                                                              SELECT "col1" FROM "test_7e94300056c8cc0_bl_tmp001" 

How is it possible to have this result ? I tried to put another column at the top with value 'DEFAULT' but it didn't work.

Any ideas ?

Thanks for help
Vincent

**Comment by hiroyuki-sato** [comment]
Hello, @Olaktal 

I don't use Redshift. I used PostgreSQL. (Use serial instead of IDENTITY)

I can insert values without id column definition. 
The following example might help. 

If not, could you tell me detail of the problem?

* Your configuration.
* Error message
* Embulk version
* Sample data

## Example


table definition.

```
create table test(id serial not null,full_name varchar(255));'
```

name.csv

```
Nikki Rippin
Maegan Koepp
Devin DuBuque
Nels Dietrich
Nash Green
Ulises Mohr
Rae Abbott DVM
Odell Kassulke
Rachael Doyle
Amiya King II
```

conf.yml

```yaml
in:
  type: file
  path_prefix: name.csv
  parser:
    type: none
    column_name: full_name
out:
  type: postgresql
  host: localhost
  user: username
  database: embulk_test
  table: test
  mode: insert
```

embulk preview 

```
+------------------+
| full_name:string |
+------------------+
|     Nikki Rippin |
|     Maegan Koepp |
|    Devin DuBuque |
|    Nels Dietrich |
|       Nash Green |
|      Ulises Mohr |
|   Rae Abbott DVM |
|   Odell Kassulke |
|    Rachael Doyle |
|    Amiya King II |
+------------------+
```


Embulk run result.


```
select * from test;
 id |   full_name
----+----------------
  1 | Nikki Rippin
  2 | Maegan Koepp
  3 | Devin DuBuque
  4 | Nels Dietrich
  5 | Nash Green
  6 | Ulises Mohr
  7 | Rae Abbott DVM
  8 | Odell Kassulke
  9 | Rachael Doyle
 10 | Amiya King II
(10 rows)
```

**Comment by Olaktal** [comment]
Hello @hiroyuki-sato ,

It works great ! But this was for example, in reality, I have more than one column in input, how to do the same with more columns ?

For example:
create table test(id serial not null,full_name varchar(255),country varchar(255));

I tried several times but I can't find the correct syntax. Can you help me out ?

Thanks

**Comment by hiroyuki-sato** [comment]
Hello, @Olaktal 

Have you every tried "Running example" on the Quick start page? 
https://github.com/embulk/embulk#running-example

If not, please try it

The following is the multi-column example.

* 1, ``embulk guess -o conf.yml seed.yml ``
* 2, modify column name (c0 -> full_name, c1 -> country)
* 3, ``embulk run conf.yml``

name.csv

```
Nikki Rippin,Republic of Korea
Maegan Koepp,Bahamas
Devin DuBuque,Zambia
Nels Dietrich,Timor-Leste
Nash Green,Reunion
Ulises Mohr,Timor-Leste
Rae Abbott DVM,Pitcairn Islands
Odell Kassulke,Senegal
Rachael Doyle,Algeria
Amiya King II,Ireland
```

seed.yml

```
in:
  type: file
  path_prefix: name.csv
  parser:
    type: csv
out:
  type: postgresql
  host: localhost
  user: username
  database: embulk_test
  table: test
  mode: insert
```

conf.yml

```
in:
  type: file
  path_prefix: name.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 0
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: full_name, type: string}
    - {name: country, type: string}
out:
  type: postgresql
  host: localhost
  user: username
  database: embulk_test
  table: test
  mode: insert
```
