### ISSUE TITLE
[Redshift] Merge mode + Parser none Identity column issue

### ISSUE THREAD

**Issue by Olaktal** [embulk/embulk#486]
Hello,

I'm using a redshift db this is my usecase:
I have multiple platforms to store ("France","Spain", ..)

create table platform(
id identity (1,1) int,
original_id varchar(2),
label varchar(50),
active int)

And I have the following data in input:
(original_id,label,active)
('FR','France',1)
('SP','Spain',1)

Original_id is unique and this is my merge key but for performance issues I want to have a integer as primary key so this is why I added an "id" column in my table "platform".

My input config is like:
  parser:
    type: none
    columns:
    - {name: original_id, type: string}
    - {name: label, type: string}
    - {name: active, type: long}

--> It should allow me to insert data into a table with an Identity column

My output config is like:
mode: merge
merge_keys: ["original_id"]

--> This should allow me to merge data if the original_id is already in the platform table, if not, insert it.

But I encountered the following message:

"Error: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: cannot set an identity column to a value"

Do you have any idea on how to solve this problem ?
I tried to add in the output part options like  "incremental: true" and "incremental_columns: [id] " but it didn't worked.
If it is not clear, do not hesitate to ask me.

Best regards,
Vincent

**Comment by hiroyuki-sato** [comment]
Do you use parser type ``none``?.
If so confirm input data with ``embulk preview``

Maybe your input data is the following.
It has not `original_id` column. 

Use parser ``csv`` instead.

```
+--------------------------+
|           payload:string |
+--------------------------+
| original_id,label,active |
|              FR,France,1 |
|               SP,Spain,1 |
|               JP,Japan,1 |
+--------------------------+
```

I succeed to merge data with the following configuration. 
(Note: I use PostgreSQL)

```sql
create table platform(
  id serial not null,
  original_id varchar(2),
  label varchar(50),
  active int
);
ALTER TABLE platform ADD PRIMARY KEY(id);
```

```yaml
in:
  type: file
  path_prefix: ./sample.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: original_id, type: string}
    - {name: label, type: string}
    - {name: active, type: long}
out:
  type: postgresql
  user: user
  table: platform
  database: embulk_test
  host: 127.0.0.1
  mode: merge
  merge_keys: ["original_id"]
```

```csv
FR,France,1
SP,Spain,1
JP,Japan,1
```
