### ISSUE TITLE
[Feature idea] multiple S3 files into a single S3 file.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#546]
For feature discussion. 

A user wants to combine multiple S3 files into a single S3 file. 
Current `file-output`  limitation is to write multiple files only.

Just idea. For example, it is a useful feature if file-output support appends mode.

Reproduce example.
This config combines multiple CSV files into a single CSV file. 
But The output is written one file data only. 

The alternative idea creates a single-file-output plugin. 

```
.
|-- csv
|   |-- sample_01.csv.gz
|   |-- sample_02.csv.gz
|   |-- sample_03.csv.gz
|   |-- sample_04.csv.gz
|   `-- sample_05.csv.gz
`-- out
    `-- test.csv
```

```yaml
in:
  type: file
  path_prefix: /private/tmp/hoge/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
#out: {type: stdout}
filters:
  - type: to_csv
out:
  type: file
  path_prefix: /tmp/hoge/out/test
  file_ext: .csv
  sequence_format: ""
  formatter:
    type: single_value

exec:
  min_output_tasks: 1
  max_threads: 1
```

Reference 
[Twitter](https://twitter.com/yoshi_ken/status/831157186722091010) (Japanese text)
