### ISSUE TITLE
Question: available variable from Liquid templating

### ISSUE THREAD

**Issue by robinkeunen** [embulk/embulk#674]
Hi,

I'm starting to use embulk at _The Food Assembly_, it looks like a fantastic piece of software! I'm already using liquid templates to get the environment variable. Are they other available liquid variable?

Specifically, I'd like to output the current date in the path_prefix. Something like:

```yaml
out:
  type: s3
  bucket: {{ env.S3_BUCKET }}
  access_key_id: {{ env.AWS_ACCESS_KEY_ID }}
  secret_access_key: {{ env.AWS_SECRET_ACCESS_KEY }}
  path_prefix: dbimport/{{ day }}/orderitem_             #  <------
  file_ext: .csv
  formatter:
    type: csv
  encoders:
    - type: gzip
```

Is that possible?

**Comment by hiroyuki-sato** [comment]
Hello, @robinkeunen 
Welcome to the Embulk project!!

Have you ever tried `{{ "now" | date: "%Y-%m-%d"  }}`?

```yaml
in:
  type: file
  path_prefix: sample/csv/{{ "now" | date: "%Y-%m-%d"  }}/sample_  # <-- HERE
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}
```

```
.
|-- config.yml.liquid
`-- sample
    |-- csv
        |-- 2017-06-14
        `-- 2017-06-15
            `-- sample_01.csv.gz
```


Reference
https://shopify.github.io/liquid/filters/date/
