### ISSUE TITLE
Environment variables can not load by Gemfile since v0.8.29.

### ISSUE THREAD

**Issue by toyama0919** [embulk/embulk#778]
Hello.
Now I am in trouble..

Up to 0.8.28, environment variables could be loaded in liquid by the following method.
But, since 0.8.29, environmental variables can not be read by the above method.

### My Gemfile

```Gemfile

source 'https://rubygems.org/'

gem 'embulk-input-...'
gem 'embulk-filter-...'
...

gem 'dotenv'

begin
  require 'dotenv'
  Dotenv.load(File.expand_path('../../.env', __FILE__))
rescue LoadError => e
rescue => e
end

```

[dotenv](https://github.com/bkeepers/dotenv) is a library that can manage environment variables with yaml.

### My .env

```.env
DATABASE_HOST=localhost
DATABASE_USER=username
DATABASE_PASS=password
DATABASE_NAME=some_database
```

### My liquid file

```
in:
  type: mysql
  host: {{ env.DATABASE_HOST }}
  user: {{ env.DATABASE_USER }}
  password: {{ env.DATABASE_PASS }}
  database: {{ env.DATABASE_NAME }}
  query: |
    select * from users limit 1

out:
  type: stdout

```

### Run embulk
```
$ embulk run -b embulk_bundle config.yml
```

Did something change around environment variables?

It is running Gemfile on things like Digdag's --params-file.
https://docs.digdag.io/command_reference.html
