### ISSUE TITLE
JSON import question

### ISSUE THREAD

**Issue by vladimarius** [embulk/embulk#918]
Hi
I'd like to import text file containing data in json format:
```
{
   "col1": 123,
   "col2": "xyz"
},
{
   "col1": 456,
   "col2": "abc"
}
```

I have created seed.yml file containing following structure:
```
in:
    type: file
    path_prefix: /path-to-file
    parser:
        type: json
out: {type: stdout}
```

When i run embulk it doesn't seem to understand the format. Please advise me how to fix this and import file containing structure listed above.
